### PR TITLE
Disable PROTIPS in CI environments

### LINKED ISSUE #108: Please no pro-tips
I get a pro-tip at the end of my tests now, and I don't want a protip at the end of my tests. Can there at least be a configuration value to turn it off?

Thanks

### PR DESCRIPTION
**Pull request by pdehaan**
Fixes #108

### CODE REVIEW

**Comment by montogeek** [comment]
Can you please merge this one? :)

**Comment by wheresrhys** [comment]
thanks for this and sorry for the delay merging

**Comment by montogeek** [comment]
Thank you so much!

**Comment by pdehaan** [comment]
@wheresrhys Could we bother you for a 4.6.1 or 4.7.0 release on npm?

**Comment by wheresrhys** [comment]
Yeah sure. It had slipped my mind

**Pull request merged**
