### PR TITLE
Add statusText to mocked response

### PR DESCRIPTION
**Pull request by timnew**
For issue #59

### CODE REVIEW

**Comment by timnew** [comment]
@wheresrhy I found you use cascaded callbacks in the test, which might hang the test if test failed, since done is never called then.

Actually `mocha` has the built-in support to promise, so you don't need to invoke `done` manually.

And you can always return a promise in the `then` callback, which will be resolved automatically, so you don't need to use the fragile cascaded callbacks.

**Comment by wheresrhys** [comment]
Thanks for this. Would you mind making a few stylistic changes

- rename statusText.js to status-text.js
- rename STATUS_TEXT to statusTextMap

**Comment by timnew** [comment]
Fixed, please check whether it is okay now.

**Comment by wheresrhys** [comment]
Yep looks good. Just needs conflicts resolved (hopefully won't be too difficult)

**Comment by timnew** [comment]
I should be easy I think 😁

**Comment by wheresrhys** [comment]
Have merged for you in another PR. Thanks for the contribution

**Pull request closed without merging**
