### PR TITLE
Document usage with ES6 modules syntax

### PR DESCRIPTION
**Pull request by MattiSG**
Related to #57.

### CODE REVIEW

**Comment by wheresrhys** [comment]
Thanks for documenting this (been waiting for a while for someone actually affected by the issue to help me out with it). 

That said, as isomorphic-fetch sets fetch as a global shouldn't `import 'isomorphic-fetch'` work? If it doesn't for you, could you tell me more about why not.

**Comment by MattiSG** [comment]
Indeed, it does work! I simply did not know about this syntax… Thanks!

**Comment by MattiSG** [comment]
Updated PR accordingly  :)

**Comment by wheresrhys** [comment]
Sorry for slow response and thanks for the update. I have a feeling this issue affects projects using require too, so will add a note after merging

**Pull request merged**
