### PR TITLE
Added support for signal option

### PR DESCRIPTION
**Pull request by dutradda**
Implements the signal checkpoint of the issue https://github.com/wheresrhys/fetch-mock/issues/239

### CODE REVIEW

**Comment by wheresrhys** [comment]
Thanks for implementing this. Wow - cancellable promises landed quickly.

Before merging I'd like to see some tests for how this impacts the `flush()` and `done()` methods. Maybe some other aspects of the API too. In particular, because generating a response can kick off a chain of microtasks, whereas `fetch` will - I assume - only ever create one, I wonder if there's potential to time the sending of the abort signal in such a way that it'd be too late to stop a genuine fetch, but would be able to intercept fetch-mock. A pretty edge case, but worth at least giving some thought to

**Comment by wheresrhys** [comment]
Hi @dutradda. Did you see my response?

**Comment by dutradda** [comment]
Hello @wheresrhys ,

thank's for the reply

I will do the tests with `flush()` and `done()` calls

**Comment by thommyhh** [comment]
@dutradda @wheresrhys What is the status here? I could really use this right now.

**Comment by wheresrhys** [comment]
@thommyhh I'm rewriting documentation for v7. Unless @dutradda does so first, I plan on completing this PR after that's done and it will be released in v7

**Pull request closed without merging**
