### PR TITLE
Implementation of asynchronous mocking

### PR DESCRIPTION
**Pull request by wheresrhys**
TODO
- tests

### CODE REVIEW

**Comment by gingermusketeer** [comment]
Was just going to ask about this. Awesome to see it in progress :)

**Comment by wheresrhys** [comment]
@gingermusketeer I was in two minds about the API as it's not a use case I have. Does it look sensible to you?

**Comment by gingermusketeer** [comment]
@wheresrhys It looks sensible to me. I will be making use of this now that it has been merged. Let you know if anything comes up

**Comment by gingermusketeer** [comment]
@wheresrhys This worked perfectly. Thanks

**Pull request merged**
