### PR TITLE
Adding core-js to devDependencies

### PR DESCRIPTION
**Pull request by WaNgeL-SaTaR**
There are the problem with npm installation of fetch-mock:

Module not found: Can't resolve 'core-js/modules/es7.string.pad-end' in '/home/myProject/node_modules/fetch-mock/es5

Works only with yarn installation.

According to https://github.com/babel/babel-preset-env/issues/304

### CODE REVIEW

**Comment by wheresrhys** [comment]
Please can you outline the problem a bit more. Which environment is the problem occurring in?

**Comment by WaNgeL-SaTaR** [comment]
I have made installation of fetch-mock in my project based on create-react-app with npm. When i want to serve it, there is error occurred: 

Module not found: Can't resolve 'core-js/modules/es7.string.pad-end' in '/home/myProject/node_modules/fetch-mock/es5

I found two ways to make it work: 
1) Use yarn
2) Install core-js as dev-dependency in my project

**Comment by wheresrhys** [comment]
Would you mind pointing me at/creating an example repo please so I can see the bug for myself. Thanks

**Comment by WaNgeL-SaTaR** [comment]
I create a repo with this problem - https://github.com/WaNgeL-SaTaR/fetch-mock-test
Just `npm start`

**Comment by wheresrhys** [comment]
which version of node? I can't recreate using node 8

**Comment by wheresrhys** [comment]
Thanks for creating that  - very helpful. The problem underlying this is that fetch-mock requires core-js at version 2 (bundled in babel-polyfill v6) whereas create-react app requires it at v1. 

I would rather find a way to only have babel-polyfill as a dev dependency if I can so will give this some thought.

**Comment by WaNgeL-SaTaR** [comment]
ok, thanks.

**Comment by m90** [comment]
Did this ever get adressed? I am running into the same issue atm and have to manually include `core-js` in my projects dependencies in order to get my tests to run.

Those are my dependencies:

```js
"dependencies": {
  "page": "^1.8.6",
  "plotly.js": "^1.39.4",
  "react": "^16.4.2",
  "react-dom": "^16.4.2",
  "react-plotly.js": "^2.2.0"
},
"devDependencies": {
  "babel-core": "^6.26.3",
  "babel-plugin-transform-object-rest-spread": "^6.26.0",
  "babel-preset-env": "^1.7.0",
  "babel-preset-react": "^6.24.1",
  "babelify": "^8.0.0",
  "budo": "^11.3.2",
  "core-js": "^2.5.7",
  "enzyme": "^3.3.0",
  "enzyme-adapter-react-16": "^1.1.1",
  "eslint": "^4.19.1",
  "eslint-config-airbnb": "^17.0.0",
  "eslint-plugin-import": "^2.13.0",
  "eslint-plugin-jsx-a11y": "^6.1.1",
  "eslint-plugin-react": "^7.10.0",
  "fetch-mock": "^6.5.2",
  "mochify": "^5.8.0"
},
```

**Comment by wheresrhys** [comment]
It's supposed to be fixed yes - babel-polyfill@6 (which ships with core-js) is a dependency of fetch-mock now. Maybe try a clean install?

**Comment by m90** [comment]
I can actually repro the issue: https://github.com/m90/fetch-mock-corejs using the set of dependencies from above.

That being said, I am also thinking that this is not something that fetch-mock is doing wrong, but rather some npm hiccup when resolving the dependencies.

**Comment by m90** [comment]
Also, just like noted by @WaNgeL-SaTaR `yarn` does correctly install things, so it's definitely a `npm` thing.

**Pull request closed without merging**
