### PR TITLE
fix: request with query params not containing string values not validated correctly

### PR DESCRIPTION
**Pull request by ayZagen**
Given the example: 
```js
const mocker = fetchMock.sandbox()

const params = {
   a: 1,
   b: 2
}

const request = mocker.mock({
  url: 'http://test.example.com',
  method: 'GET',
  query: params
}, 200);

fetch( {
   url : 'http://test.example.com?'+ qs.stringify(params),
   method: 'GET'
}).then( () => {
   assert request.called() === true   // fails
})
```

The problem is query matcher checks for passed query values without transforming them. For ex. if the passed query param is a number it will fail because received query params will be string.

### CODE REVIEW

**Comment by ayZagen** [comment]
Also related to #554

**Comment by wheresrhys** [comment]
I can see this being a convenience for developers, even though query strings, technically, can only ever be strings, so I'm in favour of the addition.

I think it is however a bit odd to coerce numbers but not boolean and null, and it also raises the question (which must be documented/implemented) of what to do with keys that exist but contain undefined.

In summary - if we start coercing _some_ values we should coerce other values where it's sensible to do so, and have clear documentation of when coercion is not applied.

I'd favour
- Booleans are coerced
- objects (including null and functions) throw an error
- undefined is treated the same as a non-existent key

Questions:
- Does that sound sensible?
- Can you think of any omissions?
- Are you happy to implement that behaviour in this PR?

**Comment by ayZagen** [comment]
You are right about other types. But regarding to your proposals I believe leaving to a module rather than implementing our own ways for dealing with it would cover most cases. We could also add a global option for letting users to use their own module. One of the possible module which users could choose is `qs` and it has really edge case difference with `querystring` module. IMHO In this state, updating type definition of query to `object` would be enough.

**Comment by ayZagen** [comment]
In addition, as you know `querystring` is a core module in Node.js and it is only serving this purpose and I believe it sticks to common URI semantics. Implementing other ways would confuse users. If users have other requirements they always can use full url matching ( which is I am currently doing right now)

**Comment by ayZagen** [comment]
> We could also add a global option for letting users to use their own module

Or we could provide an interface for passing arguments to [querystring](https://nodejs.org/api/querystring.html#querystring_querystring_parse_str_sep_eq_options)

**Comment by wheresrhys** [comment]
Ok, so it seems querystring covers most cases in a pretty intuitive way. If you wanna expand the tests & types to cover these extra types of input (boolean & undefined I think are particularly important... the others less so) I'll take a proper look at your PR when that's done.

**Comment by ayZagen** [comment]
added test cases as you requested

**Comment by wheresrhys** [comment]
Closing in favour of #557, which tweaks the docs and tests a bit

**Pull request closed without merging**
